#!/bin/zsh
if [ -z $1 ]; then
exit 1
fi
# test lastpass status
/usr/local/bin/lpass status 2>&1 > /dev/null
[ "$?" -eq "0" ] || (
/usr/local/bin/lpass login --trust lastpass@mccroreys.com 2>&1 > /dev/null
)
# security -q find-generic-password -gs $1 2>&1 |awk -F\" '/password/ {print $2}'
/usr/local/bin/lpass show "${1}" --password
